---
dev_name: bosh_kubernetes_cpi_release
latest_release_filename: "/Users/d043856/projects/bosh-kubernetes-cpi-release/dev_releases/bosh_kubernetes_cpi_release/bosh_kubernetes_cpi_release-0+dev.93.yml"
